CREATE DATABASE MyPayroll;
use MyPayroll;
CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Role ENUM('Admin', 'HR', 'Employee') NOT NULL DEFAULT 'Employee',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Isactive INT Not NULL DEFAULT 1
);

CREATE TABLE PayrollBase (
    PayrollID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    BasicSalary DECIMAL(10,2) NOT NULL,
    HRA DECIMAL(10,2) DEFAULT 0.00,
    DA DECIMAL(10,2) DEFAULT 0.00,
    OtherAllowance DECIMAL(10,2) DEFAULT 0.00,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT DEFAULT NULL,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT DEFAULT NULL,
    CONSTRAINT fk_payroll_user FOREIGN KEY (UserID) REFERENCES Users(UserID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT fk_payroll_createdby FOREIGN KEY (CreatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_payroll_updatedby FOREIGN KEY (UpdatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE LeaveRecords (
    LeaveID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    LeaveType VARCHAR(20) NOT NULL CHECK (LeaveType IN ('Casual', 'Sick', 'LOP')),
    FromDate DATE NOT NULL,
    ToDate DATE NOT NULL,
    LeaveDays INT NOT NULL CHECK (LeaveDays >= 0), -- calculated in backend
    Status  ENUM('Pending', 'Approved', 'Rejected') NOT NULL DEFAULT 'Pending',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedBy INT DEFAULT NULL,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UpdatedBy INT DEFAULT NULL,
    CONSTRAINT fk_leave_user FOREIGN KEY (UserID) REFERENCES Users(UserID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_leave_createdby FOREIGN KEY (CreatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_leave_updatedby FOREIGN KEY (UpdatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE SalaryAdjustments (
    AdjustmentID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    AdjustmentType VARCHAR(20) NOT NULL CHECK (AdjustmentType IN ('Bonus', 'Deduction')),
    Amount DECIMAL(10,2) NOT NULL CHECK (Amount >= 0),
    MonthYear VARCHAR(10) NOT NULL, -- e.g., 'Sep-2025'
    Remarks VARCHAR(255),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT DEFAULT NULL,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT DEFAULT NULL,
    CONSTRAINT fk_adjustment_user FOREIGN KEY (UserID) REFERENCES Users(UserID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT fk_adjustment_createdby FOREIGN KEY (CreatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_adjustment_updatedby FOREIGN KEY (UpdatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE PayrollRuns (
    PayrollRunID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    MonthYear VARCHAR(10) NOT NULL, -- e.g., 'Sep-2025'
    GrossSalary DECIMAL(10,2) NOT NULL CHECK (GrossSalary >= 0),
    PF DECIMAL(10,2) DEFAULT 0.00 CHECK (PF >= 0),
    ESI DECIMAL(10,2) DEFAULT 0.00 CHECK (ESI >= 0),
    TDS DECIMAL(10,2) DEFAULT 0.00 CHECK (TDS >= 0),
    Bonus DECIMAL(10,2) DEFAULT 0.00 CHECK (Bonus >= 0),
    Deduction DECIMAL(10,2) DEFAULT 0.00 CHECK (Deduction >= 0),
    NetSalary DECIMAL(10,2) NOT NULL CHECK (NetSalary >= 0),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,	
    CreatedBy INT DEFAULT NULL,
	UpdatedBy INT DEFAULT NULL,
	UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_payrollruns_user FOREIGN KEY (UserID) REFERENCES Users(UserID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT fk_payrollruns_createdby FOREIGN KEY (CreatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_payrollruns_updatedby FOREIGN KEY (UpdatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE Payslips (
    PayslipID INT AUTO_INCREMENT PRIMARY KEY,
    PayrollRunID INT NOT NULL,
    FilePath VARCHAR(255) NOT NULL,
    GeneratedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_payslip_payrollrun FOREIGN KEY (PayrollRunID) REFERENCES PayrollRuns(PayrollRunID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ComplianceRules (
    RuleID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL CHECK (NAME IN ('PF', 'TDS', 'ESI')),           
    Value DECIMAL(10,4) NOT NULL,            -- supports percentages or fixed amounts
    Description VARCHAR(255),
    EffectiveFrom DATE NOT NULL DEFAULT (CURRENT_DATE), 
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CreatedBy INT DEFAULT NULL,
	UpdatedBy INT DEFAULT NULL,
    UNIQUE KEY uq_rule_name_from (Name, EffectiveFrom),
    CONSTRAINT fk_Compliance_createdby FOREIGN KEY (CreatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_Compliance_updatedby FOREIGN KEY (UpdatedBy) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE
);
